url: https://srohatgi.github.io
baseurl: 

# Site settings
title: IntoCloudTech
email: sumeet@intocloudtech.com
description: "Work on interesting and challenging projects."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Sumeet Rohatgi
  pic: 1
  position: CEO
  social:
    - title: linkedin
      url: http://linkedin.com/in/sumeetrohatgi
    - title: github
      url: http://github.com/srohatgi
    - title: twitter
      url: https://twitter.com/sum_rtg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Fremont, CA 94539

# Build settings
markdown: kramdown
permalink: pretty
